[tool.poetry]
name = "openstates"
version = "5.6.0"
description = "core infrastructure for the openstates project"
authors = ["James Turk <james@openstates.org>"]
license = "MIT"

[tool.poetry.scripts]
os-update = 'openstates.cli.update:main'
os-initdb = 'openstates.cli.initdb:main'
os-update-computed = 'openstates.cli.update_computed:main'

[tool.poetry.dependencies]
python = "^3.6"
psycopg2-binary = "^2.8.4"
dj_database_url = "^0.5.0"
Django = ">=2.2"
scrapelib = "^1.2.0"
jsonschema = "^3.2.0"
pytz = "^2019.3"
click = "^7.1.1"
attrs = "^20.2.0"
us = "^2.0.2"
PyYAML = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
pytest-django = "^3.8.0"
coveralls = "^1.11.1"
flake8 = "^3.7.9"
coverage = {extras = ["toml"], version = "^5.0.4"}
black = "^20.8b1"

[tool.coverage.run]
omit = [
  "openstates/data/admin/*",
  "openstates/reports/admin.py",
  "openstates/utils/ansistrm.py",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
